version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.2.11
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: composer install
      - run:
          name: Run Tests
          command: composer test
