version: 2.1
executors:
  laravel-executor:
    docker:
      - image: circleci/php:8.2
    working_directory: /var/www/html

jobs:
  build:
    executor: laravel-executor
    steps:
      - checkout

      # Laravel Sailのセットアップ
      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      # Laravel Sailを使用してDockerコンテナを起動
      - run:
          name: Start Laravel Sail
          command: |
            cp .env.example .env
            docker-compose up -d

      # Composerのインストールと依存関係のインストール
      - run:
          name: Install Composer Dependencies
          command: composer install

      # Laravel Sailのセットアップ
      - run:
          name: Sail Artisan Setup
          command: |
            php artisan key:generate
            php artisan migrate
            php artisan db:seed

      # PHPUnitテストの実行
      - run:
          name: Run PHPUnit Tests
          command: vendor/bin/phpunit

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
