version: 2.1
jobs:
  build:
    docker:
      - image: php:8.2-fpm

    working_directory: ~/project

    steps:
      - checkout

      - run: cp .env.example .env
      - run: composer install
      - run: php artisan key:generate

      # Create and start Laravel Sail containers
      - run: ./vendor/bin/sail up -d

      # Run tests with Sail
      - run: ./vendor/bin/sail test

  # Add additional jobs and workflows as needed

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
